apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: base-env
entity:
  name: base-env
  type: base-env
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        manifests: |-
          secretstore-policy-configmap.yaml:
            location: namespace
            data:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: secretstore-config
              data:
                allowedSecretStoreNames: $${resources['config#secretstore'].outputs.allowed-secret-store-names}
  criteria:
  - {}